mariadb-master:
  container_name: mariadb-master
  image: jamiejackson/mariadb-replication:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=microservicespringboot
    - MYSQL_USER=rizki
    - MYSQL_PASSWORD=mufrizal

mariadb-slave:
  container_name: mariadb-slave
  image: jamiejackson/mariadb-replication:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=microservicespringboot
    - MYSQL_USER=rizki
    - MYSQL_PASSWORD=mufrizal
  links:
    - mariadb-master:master

redis-master:
  container_name: redis-master
  image: bitnami/redis:latest
  environment:
    - REDIS_REPLICATION_MODE=master
    - REDIS_PASSWORD=mufrizal

redis-slave:
  container_name: redis-slave
  image: bitnami/redis:latest
  environment:
    - REDIS_REPLICATION_MODE=slave
    - REDIS_MASTER_HOST=master
    - REDIS_MASTER_PORT_NUMBER=6379
    - REDIS_MASTER_PASSWORD=mufrizal
    - REDIS_PASSWORD=mufrizal
  links:
    - redis-master:master

server1-belajar-load-balancing:
  command: bash -c 'sleep 20 && java -Dspring.profiles.active=container -jar /app.jar'
  container_name: server1-belajar-load-balancing
  image: rizki.mufrizal/belajar.spring.boot.load.balancing
  links:
    - mariadb-master
    - redis-master
  ports:
    - 8081:8080

server2-belajar-load-balancing:
  command: bash -c 'sleep 25 && java -Dspring.profiles.active=container -jar /app.jar'
  container_name: server2-belajar-load-balancing
  image: rizki.mufrizal/belajar.spring.boot.load.balancing
  links:
    - mariadb-master
    - redis-master
  ports:
    - 8082:8080

haproxy-server:
  container_name: haproxy-server
  image: custom-haproxy
  links:
    - server1-belajar-load-balancing
    - server2-belajar-load-balancing
  ports:
    - 8083:80
    - 9001:9000