spring:

  # spring datasource jpa
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database/belajar
    username: rizki
    password: mufrizal
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  # spring hibernate
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: H2

  # jackson config
  jackson:
    serialization:
      indent_output: true

  # spring devtools
  devtools:
    livereload:
      enabled: true

  # spring thymeleaf
  thymeleaf:
    cache: false

# tomcat konfiguration
server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat

---
spring:
  profiles: container

  # spring datasource jpa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MARIADB_PORT_3306_TCP_ADDR}:${MARIADB_PORT_3306_TCP_PORT}/${MARIADB_ENV_MYSQL_DATABASE}
    username: ${MARIADB_ENV_MYSQL_USER}
    password: ${MARIADB_ENV_MYSQL_PASSWORD}
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  # spring hibernate
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # jackson config
  jackson:
    serialization:
      indent_output: true

  # spring devtools
  devtools:
    livereload:
      enabled: true

  # spring thymeleaf
  thymeleaf:
    cache: false

# tomcat konfiguration
server:
  compression:
    enabled: true